### ISSUE TITLE
Invalid account_id key

### ISSUE THREAD

**Issue by oryanpeer** [dome9/terraform-provider-dome9#23]
Hi, 

Documentation is not align with the code.

https://www.terraform.io/docs/providers/dome9/d/cloudaccount_gcp.html

On the documentation it says required argument - account_id while in the code it's reading "id" only.

data_source_dome9_cloudaccount_gcp.go

`			"id": {
				Type:     schema.TypeString,
				Required: true,
			},`

**Comment by ayalganem** [comment]
Hi, 
In order to fetch the data it should get "account_id" as you can see in the documentation, also in the code it defined as required.
<img width="489" alt="Screen Shot 2019-11-25 at 15 27 33" src="https://user-images.githubusercontent.com/51665557/69544521-948dfb80-0f98-11ea-8f0c-720c7ecda80b.png">
